# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_auto_20170113_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
